# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: job1
    steps:
    - script: echo Hello, world!
      displayName: 'Run a one-line script'
  - job: job2
    steps:
    - script: echo Hello, world!
      displayName: 'Run a one-line script'
- stage: Test
  jobs:
  - job: job1
    steps:
    - script: echo Hello, world!
      displayName: 'Run a one-line script'
  - job: job2
    steps:
    - script: echo Hello, world!
      displayName: 'Run a one-line script'
- stage: Deploy
  jobs:
  - job: job1
    steps:
    - script: echo Hello, world!
      displayName: 'Run a one-line script'
  - job: job2
    steps:
    - script: echo Hello, world!
      displayName: 'Run a one-line script'