# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- name: 1
  value: changed variable 1
- name: 2
  value: changed variable 2

stages:
- stage: Build
  jobs:
  - job: job1
    steps:
    - script: echo $(build) $(1)
      displayName: 'Run a one-line script'
  - job: job2
    steps:
    - script: echo $(build) $(2)
      displayName: 'Run a one-line script'
- stage: DeployDev
  dependsOn: Build
  jobs:
  - job: job1
    steps:
    - script: echo $(dev) $(1)
      displayName: 'Run a one-line script'
  - job: job2
    steps:
    - script: echo $(dev) $(2)
      displayName: 'Run a one-line script'
# - stage: DeployQA
#   dependsOn: Build
#   jobs:
#   - job: job1
#     steps:
#     - script: echo $(qa)1
#       displayName: 'Run a one-line script'
#   - job: job2
#     steps:
#     - script: echo $(qa)2
#       displayName: 'Run a one-line script'
# - stage: DeployProd
#   dependsOn: 
#   - DeployQA
#   - DeployDev
#   jobs:
#   - job: job1
#     steps:
#     - script: echo $(prod)1
#       displayName: 'Run a one-line script'
#   - job: job2
#     steps:
#     - script: echo $(prod)2
#       displayName: 'Run a one-line script'