apiVersion: v1
kind: ServiceAccount
metadata:
 name: sa1234
 namespace: default
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: sa1234
  annotations:
    kubernetes.io/service-account.name: sa1234
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fabric8-rbac
  namespace: default
subjects:
  - kind: ServiceAccount
    # Reference to upper's `metadata.name`
    name: sa1234
    # Reference to upper's `metadata.namespace`
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io